LIST p=18f4520
    #include<p18f4520.inc>
	CONFIG OSC = INTIO67
	CONFIG WDT = OFF
	org 0x00
INITIAL:
    TESTDATA EQU 0x000
    COUNTER EQU 0x001
    ANS EQU 0x002
    MOVLW b'00010111'
    MOVWF TESTDATA
    CLRF COUNTER
    CLRF ANS
LOOP:
    MOVLW 0x01
    ANDWF TESTDATA,WREG
    BNZ ADD
    INCF COUNTER
    RRNCF TESTDATA
    MOVLW 0x08
    SUBWF COUNTER,W
    BZ EndAdvance
    GOTO LOOP
ADD:
    INCF ANS
    INCF COUNTER
    RRNCF TESTDATA
    MOVLW 0x08
    SUBWF COUNTER,W
    BZ EndAdvance
    GOTO LOOP
EndAdvance:
    GOTO EndAdvance
START:
	end

