LIST p=18f4520
    #include<p18f4520.inc>
	CONFIG OSC = INTIO67
	CONFIG WDT = OFF
	org 0x00
INITIAL:
    ANS EQU 0x00
    TESTDATA EQU 0x01
    TESTDATATEMP EQU 0x03
    FACTER EQU 0x02
    GOTO START
ISPRIME:
    LOOP:
	INCF FACTER
	MOVFF FACTER,WREG
	CPFSGT TESTDATA
	    return
	MOVFF TESTDATA,TESTDATATEMP
	LOOP2:
	    MOVFF FACTER,WREG
	    CPFSGT TESTDATATEMP
		GOTO CHECK
	    SUBWF TESTDATATEMP,F
	    GOTO LOOP2
	
	CHECK:
	    MOVLW 0x00
	    CPFSEQ TESTDATATEMP
		GOTO LOOP
	    MOVLW 0x01
	    MOVWF ANS
	    return
START:
    MOVLW 0x29
    MOVWF TESTDATA
    MOVWF TESTDATATEMP
    MOVLW 0x01
    MOVWF FACTER
    MOVLW 0xFF
    MOVWF ANS
    rcall ISPRIME
	end


