LIST p=18f4520
    #include<p18f4520.inc>
	CONFIG OSC = INTIO67
	CONFIG WDT = OFF
	org 0x00
INITIAL:
    DIVIDEND EQU 0x010
    DIVISOR EQU 0x011
    DIVISOR_O EQU 0x012
    QUOTIENT EQU 0x000
    REMAINDER EQU 0x001
    MOVLW 0x17
    MOVWF DIVIDEND
    MOVLW 0x06
    MOVWF DIVISOR
    MOVWF DIVISOR_O
RR:
    BTFSC DIVISOR,7
	GOTO CONTINUE
    RLCF DIVISOR
    GOTO RR
RR2:
    RRNCF DIVISOR
    RLNCF QUOTIENT
CONTINUE:
    RLNCF QUOTIENT
    MOVF DIVISOR,0,0
    SUBWF DIVIDEND,WREG
    BNC  RR2
    RRNCF DIVISOR
    MOVFF WREG,DIVIDEND
    INCF QUOTIENT
    MOVF DIVISOR_O,0,0
    SUBWF DIVISOR,WREG
    BNC FINAL
    GOTO CONTINUE 
FINAL:
    MOVFF DIVIDEND ,REMAINDER
    NOP
end


